# Generated by Django 5.1.4 on 2024-12-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallettransactions_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransactions',
            name='Date',
        ),
    ]
