# Generated by Django 5.1.4 on 2024-12-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemaster',
            old_name='gamegameendtime',
            new_name='gameendtime',
        ),
        migrations.RenameField(
            model_name='gamemaster',
            old_name='gamegamestarttime',
            new_name='gamestarttime',
        ),
    ]
