# Generated by Django 5.1.4 on 2024-12-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_rename_gamegameendtime_gamemaster_gameendtime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyGames',
        ),
    ]
